### ISSUE TITLE
아이디어 문의

### ISSUE THREAD

**Issue by jjscan** [wjdgowns77/NaverCafeBackupProject#1]
안녕하세요.
우선 좋은 프로그램을 제작해주셔서 감사합니다 :)

제작자님과 비슷한 경험으로 인해 네이버카페 게시글 백업을 검색하다가 깃허브까지 오게 됐습니다.

제작자님의 프로그램은 게시물을 html 또는 pdf형식으로 변환하는 기능을 가지고 있습니다.

혹시 해당 게시물을 다른 카페로 옮기는 기능에 대해서는 구현할 계획이 없으신가요?

**Comment by wjdgowns77** [comment]
늦어서 죄송합니다...ㅠㅠ

1. 일단 네이버카페 자체 공식 api를 사용할 경우 다음과 같은 제한이 있어 개발이 어렵습니다.

   1)  [ 카페 API 사용을 위해서는, 먼저 네이버 아이디로 로그인 적용이 필요합니다. ]
   2)  [ * 처리한도 : 카페 글쓰기: 200건/일 (네이버 계정당) ]
-> 일단 가장 큰 문제로는 말씀하신 방향으로 프로그램을 개발하게 된다면 네이버카페를 사실상 복제하는 프로그램이 될 텐데, 이런 목적을 위해 네이버 측에서 "네이버 아이디로 로그인"기능을 허용해 줄지 알 수 없습니다. 
" 반드시 검수에 통과되어야 네이버 아이디로 로그인 사용이 가능합니다." (api관련 공지사항 중...)
->두번째 문제로는, 이 방향으로 프로그램을 개발하게 될 시 프로그램이 아니라 서비스가 개발되게 됩니다.
네이버 ID로 로그인 기능은 미리 입력된 [ Callback URL ]을 통해 api와 관련된 값을 반환하는데, 카페api의 목적 자체가 단순 게시글 등록을 자동화하기 위한 목적이 아닙니다.
이건 제가 서버 한대 더 돌리면 되니 별 문제는 없습니다만, 하루에 겨우 300개의 게시글을 복제할 서버를 새로 구축하기에는 무리가 따릅니다....ㅠㅠ


2. 네이버카페의 비공식적인 루트(그냥 사람처럼 글쓰기를 할 경우)를 사용할 경우 다음과 같은 자동 등록 방지를 위한 여러 설정으로 인해 개발이 어렵습니다.
![image](https://user-images.githubusercontent.com/31847906/62106439-31d56d80-b2e0-11e9-9ea3-e837d11579f4.png)
기계로 자동화 한게 아니고, 직접 손으로 빠른시간내에 글을 2개 등록하니 이렇게 등록이 되지 않았습니다.

네이버카페의 글을 열람(저장)하는 부분에 있어서는 별다른 문제가 없지만, 등록하는 부분에 있어서는 네이버가 원래 이전부터 카페에 등록되는 광고성 게시글에 워낙에 많이 시달렸기 때문에(지금도 시달리고 있음) 굉장히 까다롭습니다...ㅠㅠ

**Comment by jjscan** [comment]
제약사항에 대해서 자세하게 설명해주셔서 감사합니다.
결국 공식API를 이용한 방법에는 한계가 있다는 것을 다시 한 번 느끼고 갑니다.
