### ISSUE TITLE
v0.36 다운로드 링크 깨짐

### ISSUE THREAD

**Issue by TnStory** [wjdgowns77/NaverCafeBackupProject#2]
안녕하세요.
아직 사용해 보진 못했습니다만,   
좋은 s/w 제공해 주셔서 감사합니다.
ver0.36 버전을 다운 받으려 했습니다만, 아래 링크가 깨져 받으수가 없습니다.
https://imholic.com:8091/sharing/NWAmdlK8m

이전버전인 0.35는 다운로드가 잘 됩니다.
https://imholic.com:8081/fbsharing/3t0MsW9q

이렇게 임의로 링크를 조합해서 해 봤습니다만, 성과가 없네요. 욕심에 최신 버전을 사용하고 싶어서 메일 드립니다. 
https://imholic.com:8091/fbsharing/NWAmdlK8m

좋은 S/W 제공해 주셔서 다시한번 감사 드립니다.

**Comment by wjdgowns77** [comment]
안녕하세요?
개인 서버작업(imholic.com)을 하던 중 폴더 설정이 누락되어 링크가 깨지게 된 것 같습니다.
링크를 복구하였으니 다시 다운로드 시도를 해보시면 다운로드가 가능하실겁니다...^^

Chrome버전과 NCBP버전(정확하게는 NCBP에 포함된 Chromedriver 버전)을 맞춰 주셔야 하는데, 현재 크롬 최신버전이 89라서 아마 0.35버전은 구동이 어려우실겁니다...

감사합니다.

**Comment by TnStory** [comment]
테스트까지 잘 했습니다.

좋은 프로그램 .. 다시 한번 감사 드립니다.
